name: Deploy mdBook to External Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.52
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook

      - name: Build with mdBook
        run: mdbook build -d book
      - name: Build book in Chinese
        run: MDBOOK_BOOK__LANGUAGE=zh mdbook build -d book/zh

      - name: Deploy to External Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: vivoblueos/vivoblueos.github.io
          publish_branch: main
          publish_dir: ./book
          keep_files: true
          exclude_assets: |
            README.md
            LICENSE
            .gitignore
